version: '3.6'
services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testingwithrentals
    ports:
      - "5434:5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
  rentals-api:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_NAME=testingwithrentals
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=5432
    ports:
      - "59191:59191"
    depends_on:
    - postgres
